[(if_statement)
 (for_statement)
 (while_statement)
 (switch_statement)
 (try_statement)
 (spmd_statement)
 (function_definition)
 (arguments_statement)
 (class_definition)
 (enumeration)
 (events)
 (methods)
 (properties)
 (matrix)
 (cell)
 (comment)+] @fold
